#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

CONFIG="/config/services/zfs"

case "$1" in
  purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

    if omv_config_exists $CONFIG; then
      echo "Deleting Configuration"
      omv_config_delete $CONFIG;
    fi

    if ! omv_config_exists $CONFIG; then
      echo "Configuration Deleted"
    fi

    rm -f /etc/insserv/overrides/zfs-mount

    ;;

  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
