#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions


case "$1" in
  configure)
    SERVICE_XPATH_NAME="zfs"
    SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

    if ! omv_config_exists "${SERVICE_XPATH}"; then
      omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
      omv_config_add_element "${SERVICE_XPATH}" "autoShareNestedEnabled" "1"
      omv_config_add_element "${SERVICE_XPATH}" "autoShareNestedProperty" ""
    elif ! omv_config_exists "${SERVICE_XPATH}/autoShareNestedEnabled"; then
      omv_config_add_element "${SERVICE_XPATH}" "autoShareNestedEnabled" "0"
      omv_config_add_element "${SERVICE_XPATH}" "autoShareNestedProperty" ""    
    fi

    OVERRIDE_DIR="/etc/insserv/overrides"

    insserv -rf zfs-mount || :

    mkdir -p ${OVERRIDE_DIR}

    cat <<EOF > ${OVERRIDE_DIR}/zfs-mount
### BEGIN INIT INFO
# Provides:          zfs-mount
# Required-Start:    $local_fs zfs-import
# Required-Stop:     $local_fs zfs-import
# Default-Start:     S
# Default-Stop:      0 6
# X-Stop-After:      zfs-zed
# Short-Description: Mount ZFS filesystems and volumes
# Description: Run the 'zfs mount -a' or 'zfs umount -a' commands.
### END INIT INFO
EOF

    update-rc.d zfs-mount defaults
    /sbin/modprobe zfs

    dpkg-trigger update-fixperms
    dpkg-trigger update-locale

    ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
