#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions


case "$1" in
  configure|install|upgrade)

    if [ -f /etc/insserv/overrides/zfs-mount ]; then
        rm /etc/insserv/overrides/zfs-mount
    fi

    ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    ;;

  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0